### ISSUE TITLE
Have you seen these related projects? 

### ISSUE THREAD

**Issue by datnamer** [sinhrks/pandas-ml#45]
https://github.com/amueller/patsylearn 
by @mueller

https://github.com/paulgb/sklearn-pandas 

Maybe good ideas or best to combine forces?

**Comment by sinhrks** [comment]
Yes, I'm aware of both. 

This pkg intends to cover R's ``model.frame`` like functionality and intends to cover other packages which has sklearn like API ( ``xgboost`` is under work in #44 )

I'm interested in ``patsylearn``, but not look into its detail yet. 

``sklearn-pandas`` has smaller set of functionality and doesn't cover my needs.
